/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author ACER
 */
public class Dessert extends javax.swing.JFrame {

    private HargaBarang[] dessert = new HargaBarang[9];
    private HargaBarang[] order = new HargaBarang[4];
    /**
     * Creates new form Dessert
     */
    public Dessert() {
        initComponents();
        setDessert();
        maxOrder.setVisible(false);
        min1.setVisible(false);
        min2.setVisible(false);
        min3.setVisible(false);
        min4.setVisible(false);
    }
    
    public Dessert(HargaBarang[] order){
        
        initComponents();
        setDessert();
        
        maxOrder.setVisible(false);
        min1.setVisible(false);
        min2.setVisible(false);
        min3.setVisible(false);
        min4.setVisible(false);
        this.order = order;
        showOrder();
    }
    
    public void setDessert()
    {
        dessert[0] = new HargaBarang("Belgium Waffles With Strawberries Mint",20000);
        dessert[1] = new HargaBarang("Strawberry Tart",15000);
        dessert[2] = new HargaBarang("Berry Pancake",20000);
        dessert[3] = new HargaBarang("Cheesecake With Cherry Jelly",15000);
        dessert[4] = new HargaBarang("Cupcake Blurred",10000);
        dessert[5] = new HargaBarang("Chocolate Cake",20000);
        dessert[6] = new HargaBarang("Ice Cream With Nuts Waffer Rolls",20000);
        dessert[7] = new HargaBarang("Yogurt With Raspberry",20000);
        dessert[8] = new HargaBarang("Yogurt With Chia Seed Berries",20000);
    }
    
    public void setOrderan(HargaBarang hb)
    {
        int max = 0;
        for (int i = 0; i < 4; i++)
        {   
            if(order[i] == null)
            {
                order[i]=hb;
                max = i + 1;
                break;
            }
        }
        if(max == 4){
            maxOrder.setVisible(true);
        }
        showOrder();
    }
    
    public void showOrder()
    {
        int harga_total = 0;
        total.setText(Integer.toString(harga_total));
        
        if(order[0] != null){
            ordern4.setText(String.valueOf(this.order[0].getNama()));
            orderh4.setText(Integer.toString(this.order[0].getHarga()));
            min2.setVisible(true);
            harga_total = harga_total + order[0].getHarga();
            total.setText(Integer.toString(harga_total));
        }else{
            ordern4.setText(String.valueOf(""));
            orderh4.setText(String.valueOf(""));
            min2.setVisible(false);
            maxOrder.setVisible(false);
        }
        
        if(order[1] != null){
            ordern1.setText(String.valueOf(this.order[1].getNama()));
            orderh1.setText(Integer.toString(this.order[1].getHarga()));
            min4.setVisible(true);
            harga_total = harga_total + order[1].getHarga();
            total.setText(Integer.toString(harga_total));
        }else{
            ordern1.setText(String.valueOf(""));
            orderh1.setText(String.valueOf(""));
            min4.setVisible(false);
            maxOrder.setVisible(false);
        }
        
        if(order[2] != null){
            ordern2.setText(String.valueOf(this.order[2].getNama()));
            orderh2.setText(Integer.toString(this.order[2].getHarga()));
            min1.setVisible(true);
            harga_total = harga_total + order[2].getHarga();
            total.setText(Integer.toString(harga_total));
        }else{
            ordern2.setText(String.valueOf(""));
            orderh2.setText(String.valueOf(""));
            min1.setVisible(false);
            maxOrder.setVisible(false);
        }
        
        if(order[3] != null){
            ordern3.setText(String.valueOf(this.order[3].getNama()));
            orderh3.setText(Integer.toString(this.order[3].getHarga()));
            min3.setVisible(true);
            harga_total = harga_total + order[3].getHarga();
            total.setText(Integer.toString(harga_total));
        }else{
            ordern3.setText(String.valueOf(""));
            orderh3.setText(String.valueOf(""));
            min3.setVisible(false);
            maxOrder.setVisible(false);
        } 
    }
    
    
    public void aturOrder(int index)
    {
        for(int i = index; i < 3; i++){
            order[i]=order[i+1];
            order[i+1]= null;
        }
        showOrder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ds1 = new javax.swing.JLabel();
        ds2 = new javax.swing.JLabel();
        ds3 = new javax.swing.JLabel();
        ds4 = new javax.swing.JLabel();
        ds5 = new javax.swing.JLabel();
        ds6 = new javax.swing.JLabel();
        ds7 = new javax.swing.JLabel();
        ds8 = new javax.swing.JLabel();
        ds9 = new javax.swing.JLabel();
        maindish3 = new javax.swing.JLabel();
        appetizer3 = new javax.swing.JLabel();
        coffee3 = new javax.swing.JLabel();
        tea3 = new javax.swing.JLabel();
        min2 = new javax.swing.JLabel();
        min4 = new javax.swing.JLabel();
        min1 = new javax.swing.JLabel();
        min3 = new javax.swing.JLabel();
        ordern4 = new javax.swing.JLabel();
        orderh4 = new javax.swing.JLabel();
        ordern1 = new javax.swing.JLabel();
        orderh1 = new javax.swing.JLabel();
        ordern2 = new javax.swing.JLabel();
        orderh2 = new javax.swing.JLabel();
        ordern3 = new javax.swing.JLabel();
        orderh3 = new javax.swing.JLabel();
        maxOrder = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        checkout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        ds1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds1MouseClicked(evt);
            }
        });
        getContentPane().add(ds1);
        ds1.setBounds(370, 110, 150, 150);

        ds2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds2MouseClicked(evt);
            }
        });
        getContentPane().add(ds2);
        ds2.setBounds(560, 110, 150, 150);

        ds3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds3MouseClicked(evt);
            }
        });
        getContentPane().add(ds3);
        ds3.setBounds(760, 110, 140, 150);

        ds4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds4MouseClicked(evt);
            }
        });
        getContentPane().add(ds4);
        ds4.setBounds(370, 300, 150, 150);

        ds5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds5MouseClicked(evt);
            }
        });
        getContentPane().add(ds5);
        ds5.setBounds(560, 300, 150, 150);

        ds6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds6MouseClicked(evt);
            }
        });
        getContentPane().add(ds6);
        ds6.setBounds(760, 300, 140, 150);

        ds7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds7MouseClicked(evt);
            }
        });
        getContentPane().add(ds7);
        ds7.setBounds(374, 504, 150, 140);

        ds8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds8MouseClicked(evt);
            }
        });
        getContentPane().add(ds8);
        ds8.setBounds(570, 500, 140, 150);

        ds9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds9MouseClicked(evt);
            }
        });
        getContentPane().add(ds9);
        ds9.setBounds(760, 500, 150, 150);

        maindish3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maindish3MouseClicked(evt);
            }
        });
        getContentPane().add(maindish3);
        maindish3.setBounds(30, 170, 210, 30);

        appetizer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appetizer3MouseClicked(evt);
            }
        });
        getContentPane().add(appetizer3);
        appetizer3.setBounds(30, 210, 210, 40);

        coffee3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coffee3MouseClicked(evt);
            }
        });
        getContentPane().add(coffee3);
        coffee3.setBounds(30, 310, 200, 30);

        tea3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tea3MouseClicked(evt);
            }
        });
        getContentPane().add(tea3);
        tea3.setBounds(30, 350, 200, 40);

        min2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min2.setText("X");
        min2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min2MouseClicked(evt);
            }
        });
        getContentPane().add(min2);
        min2.setBounds(960, 170, 20, 50);

        min4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min4.setText("X");
        min4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min4MouseClicked(evt);
            }
        });
        getContentPane().add(min4);
        min4.setBounds(960, 230, 20, 50);

        min1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min1.setText("X");
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min1MouseClicked(evt);
            }
        });
        getContentPane().add(min1);
        min1.setBounds(960, 300, 20, 50);

        min3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min3.setText("X");
        min3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min3MouseClicked(evt);
            }
        });
        getContentPane().add(min3);
        min3.setBounds(960, 370, 20, 50);

        ordern4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ordern4);
        ordern4.setBounds(990, 160, 250, 40);

        orderh4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(orderh4);
        orderh4.setBounds(1170, 200, 100, 30);

        ordern1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ordern1);
        ordern1.setBounds(990, 230, 250, 40);

        orderh1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(orderh1);
        orderh1.setBounds(1170, 260, 100, 30);

        ordern2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ordern2);
        ordern2.setBounds(990, 290, 250, 40);

        orderh2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(orderh2);
        orderh2.setBounds(1170, 330, 100, 30);

        ordern3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ordern3);
        ordern3.setBounds(990, 360, 250, 40);

        orderh3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(orderh3);
        orderh3.setBounds(1170, 390, 100, 30);

        maxOrder.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        maxOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxOrder.setText("Jumlah Pesanan Mencapai Maksimum");
        getContentPane().add(maxOrder);
        maxOrder.setBounds(970, 460, 290, 70);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Rp.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1130, 590, 30, 50);

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(total);
        total.setBounds(1160, 590, 120, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(1140, 600, 110, 30);

        checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutMouseClicked(evt);
            }
        });
        getContentPane().add(checkout);
        checkout.setBounds(980, 650, 270, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home-dessert.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 746);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ds1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds1MouseClicked
        // ambil array di dessert[0] 
        setOrderan(dessert[0]);
    }//GEN-LAST:event_ds1MouseClicked

    private void ds2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds2MouseClicked
        // ambil array di dessert[1]
        setOrderan(dessert[1]);
    }//GEN-LAST:event_ds2MouseClicked

    private void ds3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds3MouseClicked
        // ambil array di dessert[2]
        setOrderan(dessert[2]);
    }//GEN-LAST:event_ds3MouseClicked

    private void ds4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds4MouseClicked
        // ambil array di dessert[3]
        setOrderan(dessert[3]);
    }//GEN-LAST:event_ds4MouseClicked

    private void ds5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds5MouseClicked
        // ambil array di dessert[4]
        setOrderan(dessert[4]);
    }//GEN-LAST:event_ds5MouseClicked

    private void ds6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds6MouseClicked
        // ambil array di dessert[5]
        setOrderan(dessert[5]);
    }//GEN-LAST:event_ds6MouseClicked

    private void ds7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds7MouseClicked
        // ambil array di dessert[6]
        setOrderan(dessert[6]);
    }//GEN-LAST:event_ds7MouseClicked

    private void ds8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds8MouseClicked
        // ambil array di dessert[7]
        setOrderan(dessert[7]);
    }//GEN-LAST:event_ds8MouseClicked

    private void ds9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds9MouseClicked
        // ambil array di dessert[8]
        setOrderan(dessert[8]);
    }//GEN-LAST:event_ds9MouseClicked

    private void maindish3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maindish3MouseClicked
        MainDish m = new MainDish(order);
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_maindish3MouseClicked

    private void appetizer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appetizer3MouseClicked
        Appetizer a = new Appetizer(order);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_appetizer3MouseClicked

    private void coffee3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coffee3MouseClicked
        Coffee c = new Coffee(order);
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_coffee3MouseClicked

    private void tea3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tea3MouseClicked
        Tea t = new Tea(order);
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_tea3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(Dessert.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void min2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min2MouseClicked
        // TODO add your handling code here:
        order[0]=null;
        aturOrder(0);
    }//GEN-LAST:event_min2MouseClicked

    private void min4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min4MouseClicked
        // TODO add your handling code here:
        order[1]=null;
        aturOrder(1);
    }//GEN-LAST:event_min4MouseClicked

    private void min1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseClicked
        // TODO add your handling code here:
        order[2]=null;
        aturOrder(2);
    }//GEN-LAST:event_min1MouseClicked

    private void min3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min3MouseClicked
        // TODO add your handling code here:
        order[3]=null;
        aturOrder(3);
    }//GEN-LAST:event_min3MouseClicked

    private void checkoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutMouseClicked
        // TODO add your handling code here:
        new CheckOut(order).setVisible(true);
    }//GEN-LAST:event_checkoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dessert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appetizer3;
    private javax.swing.JLabel checkout;
    private javax.swing.JLabel coffee3;
    private javax.swing.JLabel ds1;
    private javax.swing.JLabel ds2;
    private javax.swing.JLabel ds3;
    private javax.swing.JLabel ds4;
    private javax.swing.JLabel ds5;
    private javax.swing.JLabel ds6;
    private javax.swing.JLabel ds7;
    private javax.swing.JLabel ds8;
    private javax.swing.JLabel ds9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel maindish3;
    private javax.swing.JLabel maxOrder;
    private javax.swing.JLabel min1;
    private javax.swing.JLabel min2;
    private javax.swing.JLabel min3;
    private javax.swing.JLabel min4;
    private javax.swing.JLabel orderh1;
    private javax.swing.JLabel orderh2;
    private javax.swing.JLabel orderh3;
    private javax.swing.JLabel orderh4;
    private javax.swing.JLabel ordern1;
    private javax.swing.JLabel ordern2;
    private javax.swing.JLabel ordern3;
    private javax.swing.JLabel ordern4;
    private javax.swing.JLabel tea3;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
