/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author ACER
 */
public class MainDish extends javax.swing.JFrame {

    private HargaBarang[] mainDish = new HargaBarang[9];
    private HargaBarang[] order = new HargaBarang[4];
    /**
     * Creates new form MainDish
     */
    public MainDish() {
        initComponents();
        setMainDish();
        maxOrder.setVisible(false);
        min1.setVisible(false);
        min2.setVisible(false);
        min3.setVisible(false);
        min4.setVisible(false);
    }
    
    public MainDish(HargaBarang[] order){
        
        initComponents();
        setMainDish();
        
        maxOrder.setVisible(false);
        min1.setVisible(false);
        min2.setVisible(false);
        min3.setVisible(false);
        min4.setVisible(false);
        this.order = order;
        showOrder();
    }
    
    public void setMainDish()
    {
        mainDish[0] = new HargaBarang("Beef Satay Skewers",20000);
        mainDish[1] = new HargaBarang("Nasi Padang",15000);
        mainDish[2] = new HargaBarang("Tumeric Rice",20000);
        mainDish[3] = new HargaBarang("Meat Dish with Vegetables",40000);
        mainDish[4] = new HargaBarang("Barley Soup",30000);
        mainDish[5] = new HargaBarang("Soup with Meatballs",30000);
        mainDish[6] = new HargaBarang("Grilled Chicken Breast",35000);
        mainDish[7] = new HargaBarang("Backed Chicken Wings",35000);
        mainDish[8] = new HargaBarang("Chicken Skewers",30000);
    }
    
    public void setOrderan(HargaBarang hb)
    {
        int max = 0;
        for (int i = 0; i < 4; i++)
        {   
            if(order[i] == null)
            {
                order[i]=hb;
                max = i + 1;
                break;
            }
        }
        if(max == 4){
            maxOrder.setVisible(true);
        }
        showOrder();
    }
    
    public void showOrder()
    {
        int harga_total = 0;
        total.setText(Integer.toString(harga_total));
        
        if(order[0] != null){
            ordern4.setText(String.valueOf(this.order[0].getNama()));
            orderh4.setText(Integer.toString(this.order[0].getHarga()));
            min2.setVisible(true);
            harga_total = harga_total + order[0].getHarga();
            total.setText(Integer.toString(harga_total));
        }else{
            ordern4.setText(String.valueOf(""));
            orderh4.setText(String.valueOf(""));
            min2.setVisible(false);
            maxOrder.setVisible(false);
        }
        
        if(order[1] != null){
            ordern1.setText(String.valueOf(this.order[1].getNama()));
            orderh1.setText(Integer.toString(this.order[1].getHarga()));
            min4.setVisible(true);
            harga_total = harga_total + order[1].getHarga();
            total.setText(Integer.toString(harga_total));
        }else{
            ordern1.setText(String.valueOf(""));
            orderh1.setText(String.valueOf(""));
            min4.setVisible(false);
            maxOrder.setVisible(false);
        }
        
        if(order[2] != null){
            ordern2.setText(String.valueOf(this.order[2].getNama()));
            orderh2.setText(Integer.toString(this.order[2].getHarga()));
            min1.setVisible(true);
            harga_total = harga_total + order[2].getHarga();
            total.setText(Integer.toString(harga_total));
        }else{
            ordern2.setText(String.valueOf(""));
            orderh2.setText(String.valueOf(""));
            min1.setVisible(false);
            maxOrder.setVisible(false);
        }
        
        if(order[3] != null){
            ordern3.setText(String.valueOf(this.order[3].getNama()));
            orderh3.setText(Integer.toString(this.order[3].getHarga()));
            min3.setVisible(true);
            harga_total = harga_total + order[3].getHarga();
            total.setText(Integer.toString(harga_total));
        }else{
            ordern3.setText(String.valueOf(""));
            orderh3.setText(String.valueOf(""));
            min3.setVisible(false);
            maxOrder.setVisible(false);
        }
        
    }
    
    /*public void hargaTotal()
    {
        int harga_total = 0;
        total.setText(Integer.toString(harga_total));
        
    }*/
    
    public void aturOrder(int index)
    {
        for(int i = index; i < 3; i++){
            order[i]=order[i+1];
            order[i+1]= null;
        }
        showOrder();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        md1 = new javax.swing.JLabel();
        md2 = new javax.swing.JLabel();
        md3 = new javax.swing.JLabel();
        md4 = new javax.swing.JLabel();
        md5 = new javax.swing.JLabel();
        md6 = new javax.swing.JLabel();
        md7 = new javax.swing.JLabel();
        md8 = new javax.swing.JLabel();
        md9 = new javax.swing.JLabel();
        appetizer1 = new javax.swing.JLabel();
        dessert1 = new javax.swing.JLabel();
        coffee1 = new javax.swing.JLabel();
        tea1 = new javax.swing.JLabel();
        ordern1 = new javax.swing.JLabel();
        orderh1 = new javax.swing.JLabel();
        min1 = new javax.swing.JLabel();
        min2 = new javax.swing.JLabel();
        min3 = new javax.swing.JLabel();
        min4 = new javax.swing.JLabel();
        ordern2 = new javax.swing.JLabel();
        ordern3 = new javax.swing.JLabel();
        ordern4 = new javax.swing.JLabel();
        orderh2 = new javax.swing.JLabel();
        orderh3 = new javax.swing.JLabel();
        orderh4 = new javax.swing.JLabel();
        maxOrder = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        checkout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        md1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                md1MouseClicked(evt);
            }
        });
        getContentPane().add(md1);
        md1.setBounds(370, 110, 150, 150);

        md2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                md2MouseClicked(evt);
            }
        });
        getContentPane().add(md2);
        md2.setBounds(560, 110, 150, 150);

        md3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                md3MouseClicked(evt);
            }
        });
        getContentPane().add(md3);
        md3.setBounds(760, 110, 150, 150);

        md4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                md4MouseClicked(evt);
            }
        });
        getContentPane().add(md4);
        md4.setBounds(370, 300, 160, 150);

        md5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                md5MouseClicked(evt);
            }
        });
        getContentPane().add(md5);
        md5.setBounds(560, 300, 160, 150);

        md6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                md6MouseClicked(evt);
            }
        });
        getContentPane().add(md6);
        md6.setBounds(760, 300, 150, 150);

        md7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                md7MouseClicked(evt);
            }
        });
        getContentPane().add(md7);
        md7.setBounds(370, 500, 150, 150);

        md8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                md8MouseClicked(evt);
            }
        });
        getContentPane().add(md8);
        md8.setBounds(570, 500, 140, 150);

        md9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                md9MouseClicked(evt);
            }
        });
        getContentPane().add(md9);
        md9.setBounds(760, 500, 150, 150);

        appetizer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appetizer1MouseClicked(evt);
            }
        });
        getContentPane().add(appetizer1);
        appetizer1.setBounds(30, 210, 210, 40);

        dessert1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dessert1MouseClicked(evt);
            }
        });
        getContentPane().add(dessert1);
        dessert1.setBounds(30, 260, 200, 40);

        coffee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coffee1MouseClicked(evt);
            }
        });
        getContentPane().add(coffee1);
        coffee1.setBounds(30, 300, 190, 40);

        tea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tea1MouseClicked(evt);
            }
        });
        getContentPane().add(tea1);
        tea1.setBounds(30, 350, 180, 40);

        ordern1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ordern1);
        ordern1.setBounds(990, 230, 250, 40);

        orderh1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(orderh1);
        orderh1.setBounds(1170, 260, 100, 30);

        min1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min1.setText("X");
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min1MouseClicked(evt);
            }
        });
        getContentPane().add(min1);
        min1.setBounds(960, 300, 20, 50);

        min2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min2.setText("X");
        min2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min2MouseClicked(evt);
            }
        });
        getContentPane().add(min2);
        min2.setBounds(960, 170, 20, 50);

        min3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min3.setText("X");
        min3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min3MouseClicked(evt);
            }
        });
        getContentPane().add(min3);
        min3.setBounds(960, 370, 20, 50);

        min4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min4.setText("X");
        min4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min4MouseClicked(evt);
            }
        });
        getContentPane().add(min4);
        min4.setBounds(960, 230, 20, 50);

        ordern2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ordern2);
        ordern2.setBounds(990, 290, 250, 40);

        ordern3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ordern3);
        ordern3.setBounds(990, 360, 250, 40);

        ordern4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ordern4);
        ordern4.setBounds(990, 160, 250, 40);

        orderh2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(orderh2);
        orderh2.setBounds(1170, 330, 100, 30);

        orderh3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(orderh3);
        orderh3.setBounds(1170, 390, 100, 30);

        orderh4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(orderh4);
        orderh4.setBounds(1170, 200, 100, 30);

        maxOrder.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        maxOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxOrder.setText("Jumlah Pesanan Mencapai Maksimum");
        getContentPane().add(maxOrder);
        maxOrder.setBounds(970, 460, 290, 70);

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(total);
        total.setBounds(1160, 590, 120, 50);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Rp.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1130, 590, 30, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(1140, 600, 110, 30);

        checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutMouseClicked(evt);
            }
        });
        getContentPane().add(checkout);
        checkout.setBounds(980, 650, 270, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home-maindish.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 746);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void md1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_md1MouseClicked
        setOrderan(mainDish[0]);
    }//GEN-LAST:event_md1MouseClicked

    private void appetizer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appetizer1MouseClicked
         Appetizer a = new Appetizer(order);
         a.setVisible(true);
         dispose();
         
    }//GEN-LAST:event_appetizer1MouseClicked

    private void md2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_md2MouseClicked
        // ambil array di maindish[1] 
        setOrderan(mainDish[1]);
    }//GEN-LAST:event_md2MouseClicked

    private void md3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_md3MouseClicked
        // ambil array di maindish[2]
        setOrderan(mainDish[2]);
    }//GEN-LAST:event_md3MouseClicked

    private void md4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_md4MouseClicked
        // ambil array di maindish[3]
        setOrderan(mainDish[3]);
    }//GEN-LAST:event_md4MouseClicked

    private void md5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_md5MouseClicked
        // ambil array di maindish[4]
        setOrderan(mainDish[4]);
    }//GEN-LAST:event_md5MouseClicked

    private void md6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_md6MouseClicked
        // ambil array di maindish[5]
        setOrderan(mainDish[5]);
    }//GEN-LAST:event_md6MouseClicked

    private void md7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_md7MouseClicked
        // ambil array di maindish[6]
        setOrderan(mainDish[6]);
    }//GEN-LAST:event_md7MouseClicked

    private void md8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_md8MouseClicked
        // ambil array di maindish[7]
        setOrderan(mainDish[7]);
    }//GEN-LAST:event_md8MouseClicked

    private void md9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_md9MouseClicked
        // ambil array di maindish[8]
        setOrderan(mainDish[8]);
    }//GEN-LAST:event_md9MouseClicked

    private void dessert1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dessert1MouseClicked
        Dessert d = new Dessert(order);
        d.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_dessert1MouseClicked

    private void coffee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coffee1MouseClicked
         Coffee c = new Coffee(order);
         c.setVisible(true);
         dispose();
       
    }//GEN-LAST:event_coffee1MouseClicked

    private void tea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tea1MouseClicked
         Tea t = new Tea(order);
         t.setVisible(true);
         dispose();
         
    }//GEN-LAST:event_tea1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(MainDish.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void min2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min2MouseClicked
        // TODO add your handling code here:
        order[0]=null;
        aturOrder(0);
       
    }//GEN-LAST:event_min2MouseClicked

    private void min4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min4MouseClicked
        // TODO add your handling code here:
        order[1]=null;
        aturOrder(1);
        
    }//GEN-LAST:event_min4MouseClicked

    private void min1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseClicked
        // TODO add your handling code here:
        order[2]=null;
        aturOrder(2);
       
    }//GEN-LAST:event_min1MouseClicked

    private void min3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min3MouseClicked
        // TODO add your handling code here:
        order[3]=null;
        aturOrder(3);
        
    }//GEN-LAST:event_min3MouseClicked

    private void checkoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutMouseClicked
        // TODO add your handling code here:
        new CheckOut(order).setVisible(true);
    }//GEN-LAST:event_checkoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appetizer1;
    private javax.swing.JLabel checkout;
    private javax.swing.JLabel coffee1;
    private javax.swing.JLabel dessert1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel maxOrder;
    private javax.swing.JLabel md1;
    private javax.swing.JLabel md2;
    private javax.swing.JLabel md3;
    private javax.swing.JLabel md4;
    private javax.swing.JLabel md5;
    private javax.swing.JLabel md6;
    private javax.swing.JLabel md7;
    private javax.swing.JLabel md8;
    private javax.swing.JLabel md9;
    private javax.swing.JLabel min1;
    private javax.swing.JLabel min2;
    private javax.swing.JLabel min3;
    private javax.swing.JLabel min4;
    private javax.swing.JLabel orderh1;
    private javax.swing.JLabel orderh2;
    private javax.swing.JLabel orderh3;
    private javax.swing.JLabel orderh4;
    private javax.swing.JLabel ordern1;
    private javax.swing.JLabel ordern2;
    private javax.swing.JLabel ordern3;
    private javax.swing.JLabel ordern4;
    private javax.swing.JLabel tea1;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
